monolog:
  handlers:
    console:
      type: console
      bubble: false
      channels: ["!livebroadcaster"]
    livebroadcaster:
      type: rotating_file
      path: "%kernel.logs_dir%/%kernel.environment%-livebroadcaster.log"
      max_files: 5
      channels: [livebroadcaster]
      level: info